spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Welcome123

springdoc:
  api-docs:
    path: /swagger-ui.html

jwtSecret: mydata
jwtExpiration: 86400

